default_language_version:
  python: python3

exclude: |
  (?x)^(
    .*thirdparty/.*|
    .*-so_wrap\.(h|c)$
  )

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx|m|mm|inc|java|glsl)$
        types_or: [text]
        # exclude: |
        #   (?x)^(
        #     tests/python_build/.*|
        #     platform/android/java/lib/src/com/.*
        #   )

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx|m|mm|inc|java|glsl)$
        args: [--fix, --quiet, --use-color]
        types_or: [text]
        # exclude: |
        #   (?x)^(
        #     tests/python_build/.*|
        #     platform/android/java/lib/src/com/.*
        #   )
        additional_dependencies: [clang-tidy==18.1.1]
        require_serial: true
        stages: [manual] # Not automatically triggered, invoked via `pre-commit run --hook-stage manual clang-tidy`

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
